#!/usr/bin/env ruby
require_relative 'template'

app_path, *other_args = ARGV
if ARGV.empty? || ARGV.include?('-h') || ARGV.include?('--help')
  system('rails new -h')
  puts("\n#{Template::TEMPLATE_OPTIONS_BANNER}")
  exit
elsif ARGV.last == '-o'
  puts(Template::TEMPLATE_OPTIONS_BANNER)
  exit
elsif app_path.start_with?('-')
  abort 'First argument must be the app path'
end
other_args.prepend('--api') if ARGV.include?('worker') && !ARGV.include?('--api')

command = [
  'rails',
  'new',
  app_path,
  '-m',
  "#{__dir__}/template.rb",
  '--css',
  'tailwind',
  '--skip-action-mailbox',
  '--skip-action-text',
  '--skip-active-storage',
  '--skip-jbuilder',
  '--skip-test',
  *other_args
]

puts command.join(' ')
system(*command)
