#!/usr/bin/env ruby

TEMPLATE_OPTIONS = <<~EOS

  Template options:
    -o, [--template-options=option1,option2,...]
        # Available options:
        #
        #   - banana: scaffolds a dummy Banana resource for demo purposes
        #   - devise: adds Devise authentication and Pundit authorization
        #   - generators: adds custom generators for improved scaffolding
        #   - redis
        #   - squash: squash all commits into a single "Initial commit"
        #   - worker: removes web code (requires --api)
EOS

app_path, *other_args = ARGV
if ARGV.empty? || ARGV.include?('-h') || ARGV.include?('--help')
  system('rails new -h')
  puts(TEMPLATE_OPTIONS)
  exit
elsif ARGV.last == '-o'
  puts(TEMPLATE_OPTIONS)
  exit
elsif app_path.start_with?('-')
  abort 'First argument must be the app path'
end
other_args.prepend('--api') if ARGV.include?('worker') && !ARGV.include?('--api')

command = [
  'rails',
  'new',
  app_path,
  '-m',
  "#{__dir__}/template.rb",
  '-d',
  'postgresql',
  '--css',
  'tailwind',
  '--skip-action-cable',
  '--skip-action-mailbox',
  '--skip-action-text',
  '--skip-active-storage',
  '--skip-jbuilder',
  '--skip-test',
  '--main',
  *other_args
]

puts command.join(' ')
system(*command)
